/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapplication_myjni */

#ifndef _Included_com_example_myapplication_myjni
#define _Included_com_example_myapplication_myjni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myapplication_myjni
 * Method:    getHelloWord
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myapplication_myjni_getHelloWord
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
